# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build_rpm:
    name: Build .rpm package
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Create Release-rpm
        id: create_release
        uses: actions/create-release@v1
        env:
          MY_TOKEN: ${{ secrets.MY_TOKEN }} # This token is provided by Actions
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          body: |
            Changes in this Release
            - Create RPM
            - Upload Source RPM
          draft: false
          prerelease: false
