name: Hello rpn sign

on:
  workflow_dispatch:
  workflow_call:
  push:

env:
  TAG: "${{ github.ref_name }}"
  BUILD_NUMBER: "${{ github.run_number }}"


jobs:         
  build_rpm:
    name: Build .rpm package
    runs-on: ubuntu-latest
    permissions:
      contents: write
 
    steps:
      - name: INSTALL tools & Prepare build
        run: |
          pwd 
          sudo apt install -y rpm gpg
          wget https://rpmfind.net/linux/fedora/linux/development/rawhide/Everything/x86_64/os/Packages/c/cowsay-3.7.0-8.fc39.noarch.rpm
          ls -la
          # cat << EOF >> ~/.rpmmacros
          # %_signature gpg
          # %_gpg_path /home/runner/.gnupg
          # %_gpg_name Ascensio System SIA
          # %__gpg /usr/lib/gnupg
          # EOF
          # cat ~/.rpmmacros
          which gpg
          
      - name: Import GPG 
        uses: crazy-max/ghaction-import-gpg@v5
        with: 
          gpg_private_key: ${{ secrets.GPG_PRIVATE_KEY }}
          passphrase: ${{ secrets.PASSPHRASE }}
          
          
      - name: sign RPM 
        run: |
          gpg --list-keys
          export GPG_TTY=$(tty)
          
          rpm --define "_gpg_name Ascensio System SIA" --addsign *.rpm
          rpm --checksig *.rpm
          
      - name: Get variables
        id: get_vars
        run: |
          echo "PRODUCT=$(echo "${{ github.event.repository.name }}" |  tr '[:upper:]' '[:lower:]' )" >> $GITHUB_OUTPUT
          echo "VERSION=$(echo "${GITHUB_REF##*/}" | tr -d '[:alpha:]' )" >> $GITHUB_OUTPUT
          echo "BRANCH_NAME=$(echo ${GITHUB_REF#refs/heads/})" >> $GITHUB_OUTPUT
          echo "SOURCE_NAME=$(echo ${GITHUB_REF#refs/heads/} | tr '/' '-' )" >> $GITHUB_OUTPUT
    
    
      - uses: ncipollo/release-action@v1
        with:
          allowUpdates: true
          commit: "${{ steps.get_vars.outputs.BRANCH_NAME }}"
          tag: "${{ steps.get_vars.outputs.VERSION }}-${{ env.BUILD_NUMBER }}"
          name: DocSpace packeges release "${{ env.BUILD_NUMBER }}"
          body: Here you may find packages for DocSpace
            - .RPM
            - .DEB
          artifacts: /home/runner/work/born_to_be_root/born_to_be_root/*.rpm
