name: Hello rpn sign

on:
  workflow_dispatch:
  workflow_call:
  push:

env:
  TAG: "${{ github.ref_name }}"
  BUILD_NUMBER: "${{ github.run_number }}"


jobs:         
  build_rpm:
    name: Build .rpm package
    runs-on: ubuntu-latest
    permissions:
      contents: write
 
    steps:
      - name: pip install rpmlint
        run: |
          
          

          
