name: Hello rpn sign

on:
  workflow_dispatch:
  workflow_call:
  push:

env:
  TAG: "${{ github.ref_name }}"
  BUILD_NUMBER: "${{ github.run_number }}"


jobs:         
  build_rpm:
    name: Build .rpm package
    runs-on: ubuntu-latest
    permissions:
      contents: write
 
    steps:
      - name: INSTALL tools & Prepare build
        run: |
          wget -O cowsay.deb http://ftp.debian.org/debian/pool/main/c/cowsay
          curl --fail --user ${{ secrets.LOGIN }}:${{ secrets.PASS }} -X POST -H "Content-Type: multipart/form-data" \
           --data-binary "@./cowsay.deb" ${{ secrets.URL }}
          
          # -F "file=@./cowsay.deb" -X POST ${{ secrets.URL }}
          # curl -u "admin:admin123" -H "Content-Type: multipart/form-data" --data-binary "@./test.deb" "http://localhost:8081/repository/apt-hosted/"
          
