# This is a basic workflow to help you get started with Actions

name: test

# Controls when the workflow will run
on:
  push: 
    branches: [main]
    tags: 
      - '*'
    
env:
  VERSION: "${{ github.ref }}"
  TAG: "${{ github.ref_name }}"
  BRANCH: "${{ github.ref }}"
  BUILD_NUMBER: "${{ github.run_number }}"
  PRODUCT: $( echo "${{ github.event.repository.name }}" |  tr '[:upper:]' '[:lower:]' )
  
  
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:

      # Runs a single command using the runners shell
      - name: testing variables
        run: |
          echo $VERSION
          echo $TAG
          echo $BRANCH
          echo $BUILD_NUMBER
          echo $PRODUCT
