name: Release RPM DEB

on:
  workflow_dispatch:
  workflow_call:
  push:

env:
  TAG: "${{ github.ref_name }}"
  BUILD_NUMBER: "${{ github.run_number }}"


jobs:

  build_deb:
    name: Build .deb package
    runs-on: ubuntu-latest
    permissions:
      contents: write
      
    steps:
      - name: Get files from repository
        uses: actions/checkout@v2
              
      - name: Get variables
        id: get_vars
        run: |
          echo "PRODUCT=$(echo "${{ github.event.repository.name }}" |  tr '[:upper:]' '[:lower:]' )" >> $GITHUB_OUTPUT
          echo "VERSION=$(echo "${{ github.ref }}" | grep  -oP '\d+\.\d+\.\d+' )" >> $GITHUB_OUTPUT
          echo "BRANCH_NAME=$(echo ${GITHUB_REF#refs/heads/})" >> $GITHUB_OUTPUT
              
      - name: INSTALL tools & Prepare build /home/runner/work/DocSpace/DocSpace
        run: |
          
          sudo apt install -y dh-make nginx mysql-server rename curl
          curl -sS https://dl.yarnpkg.com/debian/pubkey.gpg | sudo apt-key add -
          echo "deb https://dl.yarnpkg.com/debian/ stable main" | sudo tee /etc/apt/sources.list.d/yarn.list
          sudo apt-get remove libnode72
          sudo apt-get clean
          declare repo_version=$(if command -v lsb_release &> /dev/null; then lsb_release -r -s; else grep -oP '(?<=^VERSION_ID=).+' /etc/os-release | tr -d '"'; fi)
          wget https://packages.microsoft.com/config/ubuntu/$repo_version/packages-microsoft-prod.deb -O packages-microsoft-prod.deb
          sudo dpkg -i packages-microsoft-prod.deb
          curl -fsSL https://deb.nodesource.com/setup_18.x | sudo -E bash -
          sudo apt install -y dotnet-sdk-7.0 yarn nodejs
          sudo npm install -g json

      - name: BUILD package DEB
        shell: bash
        run: |
          
          V="${{ steps.get_vars.outputs.VERSION }}"
          sudo sed -i "s_Duplicates)' == 'false'_Duplicates)' == 'true'_" /usr/share/dotnet/sdk/$(dotnet --version)/Sdks/Microsoft.NET.Sdk/targets/Microsoft.NET.ConflictResolution.targets 
          cd build/install/deb/ 
          rename -f -v "s/product/${{ steps.get_vars.outputs.PRODUCT }}/g" debian/* ../common/* ../common/logrotate/*
          find ../ -type f -exec sed -i "s/{{product}}/${{ steps.get_vars.outputs.PRODUCT }}/g" {} ';'
          sed -i "s/{{package_header_tag_version}}/$V.$BUILD_NUMBER/g" debian/changelog debian/control
          dpkg-buildpackage -us -uc
        

      - uses: ncipollo/release-action@v1
        with:
          allowUpdates: true
          commit: "${{ steps.get_vars.outputs.BRANCH_NAME }}"
          tag: "${{ steps.get_vars.outputs.VERSION }}-${{ env.BUILD_NUMBER }}"
          name: DocSpace packeges release "${{ env.BUILD_NUMBER }}"
          body: Here you may find packages for DocSpace
          artifacts: /home/runner/work/DocSpace/DocSpace/build/install/*.deb
          

  build_rpm:
    name: Build .rpm package
    runs-on: ubuntu-latest
    permissions:
      contents: write
 
    steps:
      - name: Get files from repository.
        uses: actions/checkout@v2

      - name: INSTALL tools & Prepare build
        run: |
          sudo apt install -y rpm gpg
          wget https://rpmfind.net/linux/fedora/linux/development/rawhide/Everything/x86_64/os/Packages/c/cowsay-3.7.0-8.fc39.noarch.rpm
          pwd 
          ls -la
          
      - name: Creat gpg sign
        run: |
          cat << EOF >> GPG-sign
          Key-Type: RSA
          Key-Length: 4096
          Name-Real: Elbakyan-Shirak
          Name-Email: el.shirak@internet.com
          Expire-Date: 0
          Passphrase: 42*Hello_I-love-you!1337
          %commit
          %echo Done
          EOF
          
          gpg --batch --gen-key GPG-sign
          gpg --list-keys
          ls -la ~/.gnupg/private-keys-v1.d/
          ls -la ~/.gnupg
          gpg --export --armor --output GPG-signOUT el.shirak@internet.com
          cat GPG-signOUT
          sudo rpm --import GPG-signOUT
          rpm -q gpg-pubkey --qf '%{name}-%{version}-%{release} --> %{summary}\n'
          
          cat << EOF >> ~/.rpmmacros
          %_signature gpg
          %_gpg_path /home/runner/.gnupg
          %_gpg_name Elbakyan-Shirak
          %__gpg /usr/bin/gpg
          EOF
          
          ls -la 
          rpm --addsign *.rpm
          rpm --checksig *.rpm
          
          
          
      - name: Get variables
        id: get_vars
        run: |
          echo "PRODUCT=$(echo "${{ github.event.repository.name }}" |  tr '[:upper:]' '[:lower:]' )" >> $GITHUB_OUTPUT
          echo "VERSION=$(echo "${GITHUB_REF##*/}" | tr -d '[:alpha:]' )" >> $GITHUB_OUTPUT
          echo "BRANCH_NAME=$(echo ${GITHUB_REF#refs/heads/})" >> $GITHUB_OUTPUT
          echo "SOURCE_NAME=$(echo ${GITHUB_REF#refs/heads/} | tr '/' '-' )" >> $GITHUB_OUTPUT
    
    
      - uses: ncipollo/release-action@v1
        with:
          allowUpdates: true
          commit: "${{ steps.get_vars.outputs.BRANCH_NAME }}"
          tag: "${{ steps.get_vars.outputs.VERSION }}-${{ env.BUILD_NUMBER }}"
          name: DocSpace packeges release "${{ env.BUILD_NUMBER }}"
          body: Here you may find packages for DocSpace
            - .RPM
            - .DEB
          artifacts: /home/runner/work/DocSpace/DocSpace/build/install/rpm/SPECS/RPMS/x86_64/*.rpm
